from PySide6 import QtCore, QtWidgets


class Ui_BatchCreateAction(object):
    def setupUi(self, BatchCreateAction):
        BatchCreateAction.setObjectName("BatchCreateAction")
        BatchCreateAction.resize(400, 300)

        self.verticalLayout = QtWidgets.QVBoxLayout(BatchCreateAction)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label = QtWidgets.QLabel(BatchCreateAction)
        self.label.setObjectName("label")
        self.label.setWordWrap(True)
        self.label.setMinimumHeight(110)
        self.verticalLayout.addWidget(self.label)

        self.directoryFrame = QtWidgets.QHBoxLayout()
        self.directoryFrame.setObjectName("directoryFrame")

        self.directoryLineEdit = QtWidgets.QLineEdit(BatchCreateAction)
        self.directoryLineEdit.setObjectName("directoryLineEdit")
        self.directoryFrame.addWidget(self.directoryLineEdit)
        self.openDirectory = QtWidgets.QPushButton(BatchCreateAction)
        self.openDirectory.setObjectName("openDirectory")
        self.directoryFrame.addWidget(self.openDirectory)
        self.verticalLayout.addLayout(self.directoryFrame)
        self.comboFrame = QtWidgets.QHBoxLayout()
        self.comboFrame.setObjectName("comboFrame")
        self.leftComboLayout = QtWidgets.QVBoxLayout()
        self.leftComboLayout.setObjectName("leftComboLayout")
        self.label_2 = QtWidgets.QLabel(BatchCreateAction)
        self.label_2.setObjectName("label_2")
        self.leftComboLayout.addWidget(self.label_2)
        self.actionComboBox = QtWidgets.QComboBox(BatchCreateAction)
        self.actionComboBox.setObjectName("actionComboBox")
        self.leftComboLayout.addWidget(self.actionComboBox)
        self.comboFrame.addLayout(self.leftComboLayout)
        self.rightComboLayout = QtWidgets.QVBoxLayout()
        self.rightComboLayout.setObjectName("rightComboLayout")
        self.label_3 = QtWidgets.QLabel(BatchCreateAction)
        self.label_3.setObjectName("label_3")
        self.rightComboLayout.addWidget(self.label_3)
        self.copyComboBox = QtWidgets.QComboBox(BatchCreateAction)
        self.copyComboBox.setObjectName("copyComboBox")
        self.rightComboLayout.addWidget(self.copyComboBox)
        self.comboFrame.addLayout(self.rightComboLayout)
        self.verticalLayout.addLayout(self.comboFrame)
        self.optionsFrame = QtWidgets.QHBoxLayout()
        self.optionsFrame.setObjectName("optionsFrame")
        self.indexLayout = QtWidgets.QVBoxLayout()
        self.indexLayout.setObjectName("indexLayout")
        self.label_4 = QtWidgets.QLabel(BatchCreateAction)
        self.label_4.setObjectName("label_4")
        self.indexLayout.addWidget(self.label_4)
        self.indexSpinBox = QtWidgets.QSpinBox(BatchCreateAction)
        self.indexSpinBox.setObjectName("indexSpinBox")
        self.indexSpinBox.setMinimum(-1)
        self.indexSpinBox.setMaximum(999)
        self.indexSpinBox.setValue(-1)
        self.indexLayout.addWidget(self.indexSpinBox)
        self.optionsFrame.addLayout(self.indexLayout)
        self.overwriteCheckbox = QtWidgets.QCheckBox(BatchCreateAction)
        self.overwriteCheckbox.setObjectName("overwriteCheckbox")
        self.overwriteCheckbox.setChecked(True)
        self.optionsFrame.addWidget(self.overwriteCheckbox)
        self.fullDataCheckbox = QtWidgets.QCheckBox(BatchCreateAction)
        self.fullDataCheckbox.setObjectName("fullDataCheckbox")
        self.fullDataCheckbox.setChecked(False)
        self.optionsFrame.addWidget(self.fullDataCheckbox)
        self.verticalLayout.addLayout(self.optionsFrame)
        self.finalizeButtonBox = QtWidgets.QDialogButtonBox(BatchCreateAction)
        self.finalizeButtonBox.setObjectName("finalizeButtonBox")
        self.finalizeButtonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Apply | QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.verticalLayout.addWidget(self.finalizeButtonBox)

        self.retranslateUi(BatchCreateAction)
        QtCore.QMetaObject.connectSlotsByName(BatchCreateAction)

    def retranslateUi(self, BatchCreateAction):
        _translate = QtCore.QCoreApplication.translate
        BatchCreateAction.setWindowTitle(_translate("BatchCreateAction", "Batch Add Action"))
        self.label.setText(_translate("BatchCreateAction",
                                      "Batch add animation action name to all FrameData.xml in destination folder and all subfolders.\n"
                                      "Will be considered a copy action until manually overwritten. The copy action MUST exist in all FrameData you write to.\n"
                                      "If an Index ID is not specified, the original index will be used. Avoid collisions with other ID\'s unless you intend to overwrite."))
        self.label_2.setText(_translate("BatchCreateAction", "Action to Apply"))
        self.label_3.setText(_translate("BatchCreateAction", "Fallback / Copy From"))
        self.label_4.setText(_translate("BatchCreateAction", "Index ID"))
        self.overwriteCheckbox.setText(_translate("BatchCreateAction", "Overwrite"))
        self.openDirectory.setText(_translate("BatchCreateAction", "..."))
        self.fullDataCheckbox.setText(_translate("BatchCreateAction", "Write Full Data"))
