

from PyQt5 import QtCore, QtGui, QtWidgets

from data import VERSION


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 879)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.actionListWidget = QtWidgets.QListWidget(self.groupBox_4)
        self.actionListWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.actionListWidget.setMaximumSize(QtCore.QSize(5000, 5000))
        self.actionListWidget.setObjectName("actionListWidget")
        self.verticalLayout_7.addWidget(self.actionListWidget)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.actionDefaultPairButton = QtWidgets.QPushButton(self.groupBox_4)
        self.actionDefaultPairButton.setMinimumSize(QtCore.QSize(45, 32))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.actionDefaultPairButton.setFont(font)
        self.actionDefaultPairButton.setObjectName("actionDefaultPairButton")
        self.horizontalLayout_7.addWidget(self.actionDefaultPairButton)
        self.actionDuplicateButton = QtWidgets.QPushButton(self.groupBox_4)
        self.actionDuplicateButton.setMinimumSize(QtCore.QSize(45, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionDuplicateButton.setFont(font)
        self.actionDuplicateButton.setObjectName("actionDuplicateButton")
        self.horizontalLayout_7.addWidget(self.actionDuplicateButton)
        self.actionDeleteButton = QtWidgets.QPushButton(self.groupBox_4)
        self.actionDeleteButton.setMinimumSize(QtCore.QSize(45, 32))
        self.actionDeleteButton.setObjectName("actionDeleteButton")
        self.horizontalLayout_7.addWidget(self.actionDeleteButton)
        self.actionAddButton = QtWidgets.QPushButton(self.groupBox_4)
        self.actionAddButton.setMinimumSize(QtCore.QSize(45, 32))
        self.actionAddButton.setObjectName("actionAddButton")
        self.horizontalLayout_7.addWidget(self.actionAddButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.loadedSheetFrameList = QtWidgets.QListWidget(self.groupBox_5)
        self.loadedSheetFrameList.setMinimumSize(QtCore.QSize(151, 100))
        self.loadedSheetFrameList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.loadedSheetFrameList.setObjectName("loadedSheetFrameList")
        self.horizontalLayout_10.addWidget(self.loadedSheetFrameList)
        self.frame = QtWidgets.QFrame(self.groupBox_5)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sheetFramePicture = QtWidgets.QLabel(self.frame)
        self.sheetFramePicture.setText("")
        self.sheetFramePicture.setObjectName("sheetFramePicture")
        self.horizontalLayout_12.addWidget(self.sheetFramePicture)
        self.horizontalLayout_10.addWidget(self.frame)
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalFrame_3 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalFrame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.playButton = QtWidgets.QPushButton(self.verticalFrame_3)
        self.playButton.setMinimumSize(QtCore.QSize(32, 35))
        self.playButton.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.playButton.setFont(font)
        self.playButton.setFlat(True)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_11.addWidget(self.playButton)
        self.frameSlider = QtWidgets.QSlider(self.verticalFrame_3)
        self.frameSlider.setMaximumSize(QtCore.QSize(339, 27))
        self.frameSlider.setMaximum(2)
        self.frameSlider.setPageStep(13)
        self.frameSlider.setProperty("value", 0)
        self.frameSlider.setSliderPosition(0)
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.frameSlider.setObjectName("frameSlider")
        self.horizontalLayout_11.addWidget(self.frameSlider)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.verticalFrame_3)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 61))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 61))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.animationSpeedLabel = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.animationSpeedLabel.setFont(font)
        self.animationSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.animationSpeedLabel.setObjectName("animationSpeedLabel")
        self.verticalLayout_9.addWidget(self.animationSpeedLabel)
        self.animationSpeedSlider = QtWidgets.QSlider(self.groupBox_6)
        self.animationSpeedSlider.setMaximum(4)
        self.animationSpeedSlider.setProperty("value", 3)
        self.animationSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationSpeedSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.animationSpeedSlider.setMinimumHeight(18)
        self.animationSpeedSlider.setObjectName("animationSpeedSlider")
        self.verticalLayout_9.addWidget(self.animationSpeedSlider)
        self.gridLayout.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.verticalFrame_3)
        self.directionGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionGroupBox.sizePolicy().hasHeightForWidth())
        self.directionGroupBox.setSizePolicy(sizePolicy)
        self.directionGroupBox.setMinimumSize(QtCore.QSize(322, 0))
        self.directionGroupBox.setObjectName("directionGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.directionGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonUpLeft = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonUpLeft.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonUpLeft.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.buttonUpLeft.setFont(font)
        self.buttonUpLeft.setObjectName("buttonUpLeft")
        self.gridLayout_2.addWidget(self.buttonUpLeft, 0, 0, 1, 1)
        self.buttonUpRight = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonUpRight.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonUpRight.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonUpRight.setFont(font)
        self.buttonUpRight.setFlat(False)
        self.buttonUpRight.setObjectName("buttonUpRight")
        self.gridLayout_2.addWidget(self.buttonUpRight, 0, 2, 1, 1)
        self.buttonUp = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonUp.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonUp.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonUp.setFont(font)
        self.buttonUp.setObjectName("buttonUp")
        self.gridLayout_2.addWidget(self.buttonUp, 0, 1, 1, 1)
        self.buttonRight = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonRight.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonRight.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonRight.setFont(font)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout_2.addWidget(self.buttonRight, 1, 2, 1, 1)
        self.buttonLeft = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonLeft.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonLeft.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonLeft.setFont(font)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout_2.addWidget(self.buttonLeft, 1, 0, 1, 1)
        self.buttonDown = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonDown.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonDown.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonDown.setFont(font)
        self.buttonDown.setObjectName("buttonDown")
        self.gridLayout_2.addWidget(self.buttonDown, 2, 1, 1, 1)
        self.buttonDownRight = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonDownRight.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonDownRight.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonDownRight.setFont(font)
        self.buttonDownRight.setObjectName("buttonDownRight")
        self.gridLayout_2.addWidget(self.buttonDownRight, 2, 2, 1, 1)
        self.buttonDownLeft = QtWidgets.QPushButton(self.directionGroupBox)
        self.buttonDownLeft.setMinimumSize(QtCore.QSize(16, 16))
        self.buttonDownLeft.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonDownLeft.setFont(font)
        self.buttonDownLeft.setObjectName("buttonDownLeft")
        self.gridLayout_2.addWidget(self.buttonDownLeft, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.directionGroupBox)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.groupBox_7)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_6.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_6.setMinimumSize(QtCore.QSize(37, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.frameIndexSpinBox = QtWidgets.QSpinBox(self.horizontalFrame_2)
        self.frameIndexSpinBox.setMinimumSize(QtCore.QSize(37, 20))
        self.frameIndexSpinBox.setObjectName("frameIndexSpinBox")
        self.horizontalLayout_6.addWidget(self.frameIndexSpinBox)
        self.verticalLayout_10.addWidget(self.horizontalFrame_2)
        self.horizontalFrame = QtWidgets.QFrame(self.groupBox_7)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalFrame)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.durationSpinBox = QtWidgets.QSpinBox(self.horizontalFrame)
        self.durationSpinBox.setMinimumSize(QtCore.QSize(37, 20))
        self.durationSpinBox.setObjectName("durationSpinBox")
        self.horizontalLayout_3.addWidget(self.durationSpinBox)
        self.verticalLayout_10.addWidget(self.horizontalFrame)
        self.mirroredCheckbox = QtWidgets.QCheckBox(self.groupBox_7)
        self.mirroredCheckbox.setMinimumSize(QtCore.QSize(0, 24))
        self.mirroredCheckbox.setStyleSheet("margin-left:10;")
        self.mirroredCheckbox.setObjectName("mirroredCheckbox")
        self.verticalLayout_10.addWidget(self.mirroredCheckbox, 0, QtCore.Qt.AlignHCenter)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(1, 2, -1, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.xSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xSpinBox.sizePolicy().hasHeightForWidth())
        self.xSpinBox.setSizePolicy(sizePolicy)
        self.xSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.xSpinBox.setMinimum(-99)
        self.xSpinBox.setObjectName("xSpinBox")
        self.horizontalLayout.addWidget(self.xSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ySpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.ySpinBox.setMinimum(-99)
        self.ySpinBox.setObjectName("ySpinBox")
        self.horizontalLayout_2.addWidget(self.ySpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_10)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.xShadowSpinbox = QtWidgets.QSpinBox(self.groupBox_8)
        self.xShadowSpinbox.setMinimum(-99)
        self.xShadowSpinbox.setObjectName("xShadowSpinbox")
        self.horizontalLayout_4.addWidget(self.xShadowSpinbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.yShadowSpinBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.yShadowSpinBox.setMinimum(-99)
        self.yShadowSpinBox.setObjectName("yShadowSpinBox")
        self.horizontalLayout_5.addWidget(self.yShadowSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.gridLayout_3.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.directionGroupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frameDownReorderButton = QtWidgets.QPushButton(self.groupBox_3)
        self.frameDownReorderButton.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frameDownReorderButton.setFont(font)
        self.frameDownReorderButton.setToolTip("")
        self.frameDownReorderButton.setObjectName("frameDownReorderButton")
        self.gridLayout_4.addWidget(self.frameDownReorderButton, 1, 2, 1, 1)
        self.animationFrameList = QtWidgets.QListWidget(self.groupBox_3)
        self.animationFrameList.setMaximumSize(QtCore.QSize(16777215, 372))
        self.animationFrameList.setObjectName("animationFrameList")
        self.gridLayout_4.addWidget(self.animationFrameList, 0, 0, 7, 2)
        self.frameDeleteButton = QtWidgets.QPushButton(self.groupBox_3)
        self.frameDeleteButton.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frameDeleteButton.setFont(font)
        self.frameDeleteButton.setObjectName("frameDeleteButton")
        self.gridLayout_4.addWidget(self.frameDeleteButton, 3, 2, 1, 1)
        self.defaultFrameButton = QtWidgets.QPushButton(self.groupBox_3)
        self.defaultFrameButton.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.defaultFrameButton.setFont(font)
        self.defaultFrameButton.setObjectName("defaultFrameButton")
        self.gridLayout_4.addWidget(self.defaultFrameButton, 4, 2, 1, 1)
        self.frameUpReorderButton = QtWidgets.QPushButton(self.groupBox_3)
        self.frameUpReorderButton.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frameUpReorderButton.setFont(font)
        self.frameUpReorderButton.setObjectName("frameUpReorderButton")
        self.gridLayout_4.addWidget(self.frameUpReorderButton, 0, 2, 1, 1)
        self.returnPointButton = QtWidgets.QPushButton(self.groupBox_3)
        self.returnPointButton.setMaximumSize(QtCore.QSize(42, 42))
        self.returnPointButton.setObjectName("returnPointButton")
        self.gridLayout_4.addWidget(self.returnPointButton, 6, 2, 1, 1)
        self.copySequenceButton = QtWidgets.QPushButton(self.groupBox_3)
        self.copySequenceButton.setMinimumSize(QtCore.QSize(16, 16))
        self.copySequenceButton.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.copySequenceButton.setFont(font)
        self.copySequenceButton.setObjectName("copySequenceButton")
        self.gridLayout_4.addWidget(self.copySequenceButton, 7, 0, 1, 1)
        self.hitPointButton = QtWidgets.QPushButton(self.groupBox_3)
        self.hitPointButton.setMaximumSize(QtCore.QSize(42, 42))
        self.hitPointButton.setObjectName("hitPointButton")
        self.gridLayout_4.addWidget(self.hitPointButton, 5, 2, 1, 1)
        self.pasteSequenceButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pasteSequenceButton.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pasteSequenceButton.setFont(font)
        self.pasteSequenceButton.setObjectName("pasteSequenceButton")
        self.gridLayout_4.addWidget(self.pasteSequenceButton, 7, 1, 1, 1)
        self.rushPointButton = QtWidgets.QPushButton(self.groupBox_3)
        self.rushPointButton.setMaximumSize(QtCore.QSize(42, 42))
        self.rushPointButton.setObjectName("rushPointButton")
        self.gridLayout_4.addWidget(self.rushPointButton, 7, 2, 1, 1)
        self.frameDuplicateButton = QtWidgets.QPushButton(self.groupBox_3)
        self.frameDuplicateButton.setMaximumSize(QtCore.QSize(42, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frameDuplicateButton.setFont(font)
        self.frameDuplicateButton.setObjectName("frameDuplicateButton")
        self.gridLayout_4.addWidget(self.frameDuplicateButton, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 1, 2, 1)
        self.horizontalLayout_9.addWidget(self.directionGroupBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecent = QtWidgets.QMenu(self.menuFile)
        self.menuRecent.setObjectName("menuRecent")
        self.menuBatch = QtWidgets.QMenu(self.menubar)
        self.menuBatch.setObjectName("menuBatch")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNone = QtWidgets.QAction(MainWindow)
        self.actionNone.setEnabled(False)
        self.actionNone.setObjectName("actionNone")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAdd_Action_Copy = QtWidgets.QAction(MainWindow)
        self.actionAdd_Action_Copy.setObjectName("actionAdd_Action_Copy")
        self.actionTrim_Copies = QtWidgets.QAction(MainWindow)
        self.actionTrim_Copies.setCheckable(True)
        self.actionTrim_Copies.setObjectName("actionTrim_Copies")
        self.actionCollapse_Singles = QtWidgets.QAction(MainWindow)
        self.actionCollapse_Singles.setCheckable(True)
        self.actionCollapse_Singles.setObjectName("actionCollapse_Singles")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionTrim_Copies)
        self.menuFile.addAction(self.actionCollapse_Singles)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuBatch.addAction(self.actionAdd_Action_Copy)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBatch.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"MD Frame Editor ({VERSION})"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Action Animations"))
        self.actionDefaultPairButton.setText(_translate("MainWindow", "⌧"))
        self.actionDuplicateButton.setText(_translate("MainWindow", "⧉"))
        self.actionDeleteButton.setText(_translate("MainWindow", "-"))
        self.actionAddButton.setText(_translate("MainWindow", "+"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Loaded Sheet Frames"))
        self.playButton.setText(_translate("MainWindow", "⏯"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Animation Speed"))
        self.animationSpeedLabel.setText(_translate("MainWindow", "1x"))
        self.directionGroupBox.setTitle(_translate("MainWindow", "Direction"))
        self.buttonUpLeft.setText(_translate("MainWindow", "🡔"))
        self.buttonUpRight.setText(_translate("MainWindow", "🡕"))
        self.buttonUp.setText(_translate("MainWindow", "🡑"))
        self.buttonRight.setText(_translate("MainWindow", "🡒"))
        self.buttonLeft.setText(_translate("MainWindow", "🡐"))
        self.buttonDown.setText(_translate("MainWindow", "🡓"))
        self.buttonDownRight.setText(_translate("MainWindow", "🡖"))
        self.buttonDownLeft.setText(_translate("MainWindow", " 🡗"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Frame Data"))
        self.label_6.setText(_translate("MainWindow", "Frame"))
        self.label.setText(_translate("MainWindow", "Duration"))
        self.mirroredCheckbox.setText(_translate("MainWindow", "Horizontal Flip"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sprite Offsets"))
        self.label_3.setText(_translate("MainWindow", "X:"))
        self.label_4.setText(_translate("MainWindow", "Y:"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Shadow Offsets"))
        self.label_2.setText(_translate("MainWindow", "X:"))
        self.label_5.setText(_translate("MainWindow", "Y:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Animation Sequence"))
        self.frameDownReorderButton.setText(_translate("MainWindow", "🡓"))
        self.frameDeleteButton.setToolTip(_translate("MainWindow", "Delete Frame"))
        self.frameDeleteButton.setText(_translate("MainWindow", "-"))
        self.defaultFrameButton.setToolTip(_translate("MainWindow", "Restore Selected Frame Data"))
        self.defaultFrameButton.setText(_translate("MainWindow", "↻"))
        self.frameUpReorderButton.setText(_translate("MainWindow", "🡑"))
        self.returnPointButton.setToolTip(_translate("MainWindow", "Set Return Frame"))
        self.returnPointButton.setText(_translate("MainWindow", "RTF"))
        self.copySequenceButton.setToolTip(_translate("MainWindow", "Copy Sequence"))
        self.copySequenceButton.setText(_translate("MainWindow", "⎘"))
        self.hitPointButton.setToolTip(_translate("MainWindow", "Set Hit Frame"))
        self.hitPointButton.setText(_translate("MainWindow", "HF"))
        self.pasteSequenceButton.setToolTip(_translate("MainWindow", "Paste Sequence"))
        self.pasteSequenceButton.setText(_translate("MainWindow", "📋"))
        self.rushPointButton.setToolTip(_translate("MainWindow", "Set Rush Frame"))
        self.rushPointButton.setText(_translate("MainWindow", "RF"))
        self.frameDuplicateButton.setToolTip(_translate("MainWindow", "Duplicate Frame"))
        self.frameDuplicateButton.setText(_translate("MainWindow", "⧉"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRecent.setTitle(_translate("MainWindow", "Recent"))
        self.menuBatch.setTitle(_translate("MainWindow", "Batch"))
        self.actionLoad.setText(_translate("MainWindow", "Open"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionNone.setText(_translate("MainWindow", "None"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionAdd_Action_Copy.setText(_translate("MainWindow", "Add Action Copy"))
        self.actionTrim_Copies.setText(_translate("MainWindow", "Trim Copies"))
        self.actionCollapse_Singles.setText(_translate("MainWindow", "Collapse Singles"))
